export const VISIT_STATUS = {
  REGISTERED: 'REGISTERED',
  POS1_IN_PROGRESS: 'POS1_IN_PROGRESS',
  POS1_COMPLETE: 'POS1_COMPLETE',
  POS2_IN_PROGRESS: 'POS2_IN_PROGRESS',
  POS2_COMPLETE: 'POS2_COMPLETE',
  POS3_IN_PROGRESS: 'POS3_IN_PROGRESS',
  POS3_COMPLETE: 'POS3_COMPLETE',
  POS4_IN_PROGRESS: 'POS4_IN_PROGRESS',
  POS4_COMPLETE: 'POS4_COMPLETE',
  POS5_IN_PROGRESS: 'POS5_IN_PROGRESS',
  POS5_COMPLETE: 'POS5_COMPLETE',
  POS6_IN_PROGRESS: 'POS6_IN_PROGRESS',
  POS6_COMPLETE: 'POS6_COMPLETE',
  POS7_IN_PROGRESS: 'POS7_IN_PROGRESS',
  FINALIZED: 'FINALIZED',
  CANCELLED: 'CANCELLED',
};

export const STATUS_LABEL = {
  [VISIT_STATUS.REGISTERED]: 'Terdaftar',
  [VISIT_STATUS.POS1_IN_PROGRESS]: 'Pos 1 diproses',
  [VISIT_STATUS.POS1_COMPLETE]: 'Pos 1 selesai',
  [VISIT_STATUS.POS2_IN_PROGRESS]: 'Pos 2 diproses',
  [VISIT_STATUS.POS2_COMPLETE]: 'Pos 2 selesai',
  [VISIT_STATUS.POS3_IN_PROGRESS]: 'Pos 3 diproses',
  [VISIT_STATUS.POS3_COMPLETE]: 'Pos 3 selesai',
  [VISIT_STATUS.POS4_IN_PROGRESS]: 'Pos 4 diproses',
  [VISIT_STATUS.POS4_COMPLETE]: 'Pos 4 selesai',
  [VISIT_STATUS.POS5_IN_PROGRESS]: 'Pos 5 diproses',
  [VISIT_STATUS.POS5_COMPLETE]: 'Pos 5 selesai',
  [VISIT_STATUS.POS6_IN_PROGRESS]: 'Pos 6 diproses',
  [VISIT_STATUS.POS6_COMPLETE]: 'Pos 6 selesai',
  [VISIT_STATUS.POS7_IN_PROGRESS]: 'Pos 7 diproses',
  [VISIT_STATUS.FINALIZED]: 'Selesai final',
  [VISIT_STATUS.CANCELLED]: 'Dibatalkan',
};

export function getVisitStatusLabel(status) {
  return STATUS_LABEL[status] || status || '-';
}
