import { VISIT_STATUS } from './workflowStatus';

export const ALLOWED_TRANSITIONS = {
  [VISIT_STATUS.REGISTERED]: [VISIT_STATUS.POS1_IN_PROGRESS, VISIT_STATUS.POS1_COMPLETE, VISIT_STATUS.CANCELLED],
  [VISIT_STATUS.POS1_IN_PROGRESS]: [VISIT_STATUS.POS1_COMPLETE, VISIT_STATUS.CANCELLED],
  [VISIT_STATUS.POS1_COMPLETE]: [VISIT_STATUS.POS2_IN_PROGRESS, VISIT_STATUS.POS2_COMPLETE],
  [VISIT_STATUS.POS2_IN_PROGRESS]: [VISIT_STATUS.POS2_COMPLETE],
  [VISIT_STATUS.POS2_COMPLETE]: [VISIT_STATUS.POS3_IN_PROGRESS, VISIT_STATUS.POS3_COMPLETE],
  [VISIT_STATUS.POS3_IN_PROGRESS]: [VISIT_STATUS.POS3_COMPLETE],
  [VISIT_STATUS.POS3_COMPLETE]: [VISIT_STATUS.POS4_IN_PROGRESS, VISIT_STATUS.POS4_COMPLETE],
  [VISIT_STATUS.POS4_IN_PROGRESS]: [VISIT_STATUS.POS4_COMPLETE],
  [VISIT_STATUS.POS4_COMPLETE]: [VISIT_STATUS.POS5_IN_PROGRESS, VISIT_STATUS.POS5_COMPLETE],
  [VISIT_STATUS.POS5_IN_PROGRESS]: [VISIT_STATUS.POS5_COMPLETE],
  [VISIT_STATUS.POS5_COMPLETE]: [VISIT_STATUS.POS6_IN_PROGRESS, VISIT_STATUS.POS6_COMPLETE],
  [VISIT_STATUS.POS6_IN_PROGRESS]: [VISIT_STATUS.POS6_COMPLETE],
  [VISIT_STATUS.POS6_COMPLETE]: [VISIT_STATUS.POS7_IN_PROGRESS, VISIT_STATUS.FINALIZED],
  [VISIT_STATUS.POS7_IN_PROGRESS]: [VISIT_STATUS.FINALIZED],
  [VISIT_STATUS.FINALIZED]: [],
  [VISIT_STATUS.CANCELLED]: [],
};

export function canTransition(fromStatus, toStatus) {
  if (!fromStatus || fromStatus === toStatus) return true;
  return ALLOWED_TRANSITIONS[fromStatus]?.includes(toStatus) || false;
}

export function assertCanTransition(fromStatus, toStatus) {
  if (!canTransition(fromStatus, toStatus)) {
    throw new Error(`Transisi status tidak valid: ${fromStatus} -> ${toStatus}`);
  }
}

export function canPrintFinalReport(visit) {
  return visit?.status === VISIT_STATUS.FINALIZED;
}
