// BBL
const headersBBL = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
,
  "Berat Badan Lahir (gram)",
  "Panjang Badan Lahir (cm)",
  "Berat Badan saat ini (gram)",
  "hasil pemeriksaan pulse oksimetri pada tangan kanan (PJB1)",
  "hasil pemeriksaan Pulse Oksimetri pada kaki  (PJB2)",
  "Hasil Pemeriksaan Penyakit Jantung Bawaan",
  "Pengambilan darah tumit",
  "hasil pemeriksaan laboratorium Hipotiroid Kongenital",
  "hasil pemeriksaan laboratorium G6PD",
  "Skrining Hiperplasia Adrenal Kongenital (HAK)- hasil pemeriksaan laboratorium",
  "Apakah dilakukan tes konfrimasi SHK (hanya untuk TSH >20)",
  "Tes Konfirmasi SHK ",
  "Apakah dilakukan tes konfirmasi Defisiensi G6PD?",
  "Hasil tes konfirmasi Defisiensi G6PD",
  "Apakah dilakukan tes konfirmasi skrining HAK?",
  "Hasil tes konfirmasi Defisiensi G6PD",
  " Edukasi Kelainan Saluran Empedu",
  "Tanggal Pemeriksaan (DD/MM/YYYY)",
  "Pemeriksaan ikterus pada bayi",
  "Hasil pemeriksaan tinja (lihat buku KIA)",
  "Tanggal Pemeriksaan (DD/MM/YYYY)",
  "Pemeriksaan ikterus pada bayi",
  "Hasil pemeriksaan tinja (lihat buku KIA)"
];

// Balita 1 tahun
const headersBalita1tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
,
  "Apakah anak Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah berat badan anak Anda turun tanpa alasan yang jelas?",
  "Apakah berat badan anak Anda tidak naik dalam dua bulan terakhir?",
  "Apakah anak Anda tidak atau berkurang nafsu makan?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Berat Badan (kg)",
  "Tinggi Badan (cm)",
  "BB/U",
  "PB/U atau TB/U",
  "BB/PB atau BB/TB",
  "Lingkar kepala ",
  "Hasil Pemeriksaan KPSP",
  "Hasil Tes Daya Dengar",
  "Pemeriksaan Pupil Putih",
  "Pemeriksaan karies gigi ",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Demam yang tidak diketahui penyebabnya >= 2 pekan",
  "Pembesaran kelenjar limfe kolli, aksila, inguinal",
  "Pembengkakan tulang/sendi panggul, lutut",
  "Indurasi Tes Mantoux ",
  "Hasil Tes Mantoux",
  "Hasil Skoring TB Anak - dengan kontak (all)"
];

// Balita 2 tahun
const headersBalita2tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
,
  "Apakah anak Anda memiliki satu atau lebih kondisi berikut ini: 
1) Masalah interaksi dengan orang lain seperti kontak mata tidak adekuat; 
2) Masalah bahasa dan bicara seperti kosakata bermakna kurang dari 50 dan anak belum mampu merangkai kata, belum bisa menunjuk sesuatu, belum paham instruksi sederhana, atau bicara bahasa planet; 
3) Memiliki perilaku berulang tanpa tujuan atau perilaku aneh seperti senang melihat benda berputar, menjejerkan mainan, gerakan stereotipik (flapping, clapping, body rocking), preokupasi terhadap suatu benda, masalah sensoris",
  "Apakah anak Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah berat badan anak Anda turun tanpa alasan yang jelas?",
  "Apakah berat badan anak Anda tidak naik dalam dua bulan terakhir?",
  "Apakah anak Anda tidak atau berkurang nafsu makan?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Risiko Tuberkulosis Anak",
  "Berat Badan (kg)",
  "Tinggi Badan (cm)",
  "BB/U",
  "PB/U atau TB/U",
  "BB/PB atau BB/TB",
  "Lingkar kepala ",
  "Hasil Pemeriksaan KPSP",
  "M-CHAT-REVISED - Jika terindikasi terlambat bicara, ada gangguan komunikasi atau interaksi sosial dan perilaku yang berulang-ulang",
  "Hasil Tes Daya Dengar",
  "Pemeriksaan Pupil Putih",
  "Pemeriksaan karies gigi ",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Demam yang tidak diketahui penyebabnya >= 2 pekan",
  "Pembesaran kelenjar limfe kolli, aksila, inguinal",
  "Pembengkakan tulang/sendi panggul, lutut",
  "Indurasi Tes Mantoux ",
  "Hasil Tes Mantoux",
  "Hasil Skoring TB Anak - dengan kontak (all)",
  "Pemeriksaan gula darah sewaktu",
  "Rapid test Hemoglobin",
  "Hasil Pemeriksaan Hemoglobin (Hb) dalam g/dL",
  "Hasil Pemeriksaan MCV",
  "Hasil Pemeriksaan MCH",
  "Hasil Pemeriksaan Eritrosit / RBC Count",
  "Hasil Pemeriksaan Red cell distribution width (RDW)"
];

// Balita 3-6 tahun
const headersBalita36tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
,
  "Apakah anak Anda memiliki satu atau lebih kondisi berikut ini : 
1) Sering tantrum (mengganggu aktivitas sehari-hari) ; 
2) Mudah menangis atau marah tanpa alasan yang jelas; 
3) memukul, menggigit atau mendorong orang lain tanpa alasan yang jelas; 
4) Perubahan emosi/perilaku yang menimbulkan gangguan",
  "Apakah anak Anda memiliki satu atau lebih kondisi berikut ini : 
1) ⁠Anak tidak bisa duduk tenang; 
2) ⁠Anak selalu bergerak tanpa tujuan dan tanpa mengenal lelah; 
3) ⁠Suasana hati sangat mudah berubah;
 4) Emosi anak meledak-ledak/impulsif",
  "Apakah anak Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah berat badan anak Anda turun tanpa alasan yang jelas?",
  "Apakah berat badan anak Anda tidak naik dalam dua bulan terakhir?",
  "Apakah anak Anda tidak atau berkurang nafsu makan?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Risiko Tuberkulosis Anak",
  "Apakah ada anggota keluarga kandung  Anda dinyatakan menderita Talasemia,  atau kelainan darah atau pernah menjalani transfusi darah secara rutin?",
  "Apakah ada anggota keluarga  kandung Anda dinyatakan sebagai pembawa sifat talasemia (mereka yang memiliki genetik yang tidak normal sehingga berpotensi menurunkan penyakit Talasemia)?",
  "Faktor Risiko Talasemia ",
  "Apakah anak Anda sering lapar atau banyak makan dalam 1 bulan terakhir?",
  "Apakah anak Anda sering haus atau banyak minum dalam 1 bulan terakhir?",
  "Apakah anak Anda sering pipis dalam 1 bulan terakhir?",
  "Apakah anak Anda sering mengompol dalam 1 bulan terakhir?",
  "Apakah berat badan  anak Anda turun secara drastis ?",
  "Apakah orang tua memiliki  riwayat penyakit diabetes?",
  "Keluhan & Gejala DM",
  "Berat Badan (kg)",
  "Tinggi Badan (cm)",
  "BB/U",
  "PB/U atau TB/U",
  "BB/PB atau BB/TB",
  "Lingkar kepala ",
  "Hasil Pemeriksaan KPSP",
  "Hasil pemeriksaan Kuesioner Masalah Perilaku dan Emosional (KMPE) - Jika terindikasi memiliki masalah perilaku dan emosi",
  "Hasil Pemeriksaan Gangguan Pemusatan Perhatian dan Hiperaktivitas (GPPH) - bila ada indikasi",
  "Hasil Tes Daya Dengar",
  "Hasil Tes daya Lihat",
  "Hasil Pemeriksaan karies gigi ",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Demam yang tidak diketahui penyebabnya >= 2 pekan",
  "Pembesaran kelenjar limfe kolli, aksila, inguinal",
  "Pembengkakan tulang/sendi panggul, lutut",
  "Indurasi Tes Mantoux ",
  "Hasil Tes Mantoux",
  "Hasil Skoring TB Anak - dengan kontak (all)",
  "Pemeriksaan gula darah sewaktu",
  "Hasil Pemeriksaan Hemoglobin (Hb) dalam g/dL",
  "Hasil Pemeriksaan MCV",
  "Hasil Pemeriksaan MCH",
  "Hasil Pemeriksaan Eritrosit / RBC Count",
  "Hasil Pemeriksaan Red cell distribution width (RDW)"
];

// Laki-laki 18-24 tahun
const headersLakilaki1824tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Gula Darah Puasa (GDP) ",
  "Gula Darah 2 Jam PP ",
  "Pemeriksaan Gula Darah Lanjutan (HbA1C)",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV"
];

// Laki-laki 25-39 tahun
const headersLakilaki2539tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Gula Darah Puasa (GDP) ",
  "Gula Darah 2 Jam PP ",
  "Pemeriksaan Gula Darah Lanjutan (HbA1C)",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV"
];

// Laki-laki 40-44 tahun
const headersLakilaki4044tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)"
];

// Laki-laki 45-59 tahun
const headersLakilaki4559tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Kanker - Usus (SM)",
  "Riwayat Merokok - APCS",
  "Skor APCS",
  "Usia - skor APCS",
  "Jenis Kelamin - skor APCS",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Kesediaan Colok dubur",
  "Hasil Colok Dubur ",
  "Hasil Darah Samar",
  "Jenis Kelamin ",
  "Usia",
  "Apakah pernah didiagnosis/menderita kanker?",
  "Apakah ada keluarga (ayah/ibu/saudara kandung) didiagnosis/menderita kanker sebelumnya?",
  "Riwayat merokok/paparan asap rokok",
  "Riwayat tempat kerja mengandung zat karsinogenik (Pertambangan/ pabrik/ bengkel/ garmen/ bangunan/ laboratorium/ sopir/ galangan kapal, dll)?",
  "Lingkungan tempat tinggal berpotensi tinggi (lingkungan dekat pabrik/pertambangan/buangan sampah, dll)?",
  "Lingkungan dalam rumah yang tidak sehat (ventilasi buruk/atap dari asbes/lantai tanah, dapur tungku, dll)?",
  "Pernah didiagnosis penyakit paru kronik?",
  "Skrining Kanker Paru
intepretasi",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)"
];

// Perempuan 18-24 tahun
const headersPerempuan1824tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV"
];

// Perempuan 25-29 tahun
const headersPerempuan2529tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV"
];

// Perempuan 30-39 tahun
const headersPerempuan3039tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Apakah pernah melakukan hubungan intim/seksual?",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Pilih jenis pemeriksaan yang dilakukan",
  "Hasil pemeriksaan SADANIS",
  "Hasil pemeriksaan USG Payudara",
  "Pemeriksaan Inspekulo",
  "Pemeriksaan Inspeksi Visual Asam Asetat (IVA)",
  "Isi hasil pemeriksaan DNA HPV",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV"
];

// Perempuan 40-59 tahun
const headersPerempuan4059tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Apakah pernah melakukan hubungan intim/seksual?",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Hasil Pemeriksaan Rapid Test Sifilis",
  "Hasil Pemeriksaan Rapid Test HIV",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)",
  "Pilih jenis pemeriksaan yang dilakukan",
  "Hasil pemeriksaan SADANIS",
  "Hasil pemeriksaan USG Payudara",
  "Pemeriksaan Inspekulo",
  "Pemeriksaan Inspeksi Visual Asam Asetat (IVA)",
  "Isi hasil pemeriksaan DNA HPV"
];

// Laki-laki >=60 tahun
const headersLakilaki60tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Kanker - Usus (SM)",
  "Riwayat Merokok - APCS",
  "Skor APCS",
  "Usia - skor APCS",
  "Jenis Kelamin - skor APCS",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Apakah dapat mengingat tiga kata: bunga, pintu, nasi (contoh)?",
  "Tanggal berapakah hari ini secara lengkap (tanggal/bulan/tahun)? atau- Dimanakah Anda saat ini (Puskesmas, rumah, klinik, dll)?",
  "Apakah peserta dapat mengingat tiga kata sebelumnya?",
  "Interpretasi SKILAS Penurunan Kognitif",
  "Mintalah pasien untuk mendengarkan dengan cermat dan mengingat tiga kata dgn pilihan : versi 1: Pisang, bulan, kursi  ; versi 2 ; pemimpin, musim meja  ; versi 3 : desa, dapur, bayi",
  "Katakan seluruh frase berikut sesuai urutannya:  “Tolong gambar sebuah jam pada lembar ini. Mulailah dengan menggambar sebuah lingkaran besar. Kemudian, tuliskan angka-angka pada lingkaran dan atur jarum jam mengarah pukul 11:10 (11 lewat 10 menit).”Bila subjek tidak dapat menyelesaikan gambar jam dalam waktu 3 menit, hentikan pemeriksaan langkah ini dan lanjut ke langkah ke-3.\"",
  "Mintalah pasien untuk MENGULANG 3 kata yang disebutkan pada pertanyaan no 1",
  "Intepretasi Mini-Cog",
  "Apakah klien/pasien lansia mengalami kesulitan dalam membuat keputusan? Misalnya tidak mampu memberi saran dengan benar, tidak mampu mengurus keuangan, membeli hadiah yang tidak layak untuk orang lain, bermasalah dengan pemikiran?",
  "Apakah klien/pasien lansia anda sudah tidak menekuni hobi/ kegiatan yang sebelumnya disenangi? Misalnya merajut, menjahit, berkebun, memasak kue, membaca buku, bermain catur, memainkan alat musik atau bernyanyi?",
  "Apakah keluarga anda mengulang-ngulang pertanyaan, cerita atau pernyataan yang sama?",
  "Apakah klien/pasien lansia mengalami kesulitan belajar menggunakan perkakas dan peralatan? Seperti TV, radio, komputer, microwave, remote control, setrika, blender?",
  "Apakah klien/pasien lansia lupa nama bulan atau tahun?",
  "Apakah klien/pasien lansia mengalami kesulitan mengatur keuangan? Misalnya membayar rekening air/listrik, periksa buku cek, pajak pendapatan, mengambil yang pensiun di bank?",
  "Apakah klien/pasien lansia mengalami kesulitan mengingat janji terhadap orang lain?",
  "Apakah klien/pasien lansia sehari-harinya mengalami gangguan memori dan pemikiran yang konsisten? Misalnya lupa meletakkan kaca mata, kunci kendaraan, meletakkan barang tidak sesuai pada tempatnya?",
  "Interpretasi AD-8",
  "Tes Berdiri di kursi: Berdiri dari kursi lima kali tanpa bantuan tangan. Apakah orang tersebut dapat berdiri dari kursi utuh sebanyak lima kali dalam 14 detik ?",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri berdampingan",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri semi tandem",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri Tandem",
  "tes kecepatan berjalan: Waktu untuk berjalan sejauh empat meter",
  "Tes berdiri dari kursi: Waktu untuk bangkit dari kursi lima kali",
  "Interpretasi SPBB",
  "Apakah berat badan Anda berkurang >3 kg dalam 3 bulan terakhir atau pakaian menjadi lebih longgar?",
  "Apakah Anda hilang nafsu makan Atau mengalami kesulitan makan (misal batuk atau tersedak saat makan, menggunakan selang makan/sonde)?",
  "Apakah ukuran lingkar lengan atas (LiLA) <21 cm?",
  "Interpretasi SKILAS Malnutrisi",
  "Apakah anda mengalami penurunan asupan makanan dalam 3 bulan terakhir disebabkan kehilangan nafsu makan, gangguan saluran cerna, kesulitan mengunyah atau menelan?",
  "Penurunan berat badan dalam tiga bulan terakhir ?",
  "Kemampuan melakukan mobilitas ?",
  "Menderita stress psikologis atau penyakit akut dalam tiga bulan terakhir ?",
  "Mengalami masalah neuropsikologis?",
  "Berapa Nilai IMT (Indeks Massa Tubuh)?",
  "\"Berapa Lingkar Betis? Pertanyaan ini hanya berlaku jika dilapangan tidak ada pengukuran BB dan TB (IMT), jika sdh ada IMT, maka pertanyaan ini tidak perlu ada\"",
  "Interpretasi MNASF",
  "Apakah dalam 2 minggu terakhir Anda merasa sedih, tertekan, atau putus asa?",
  "Apakah dalam 2 minggu terakhir Anda sedikit minat atau kesenangan dalam melakukan sesuatu?",
  "Hasil Skrining Gejala Depresi",
  "Perasaan dalam 2 Minggu terakhir : Apakah anda pada dasarnya puas dengan kehidupan anda?",
  "Menggambarkan perasaan pasien selama dua minggu terakhir:: Apakah anda sering merasa bosan?",
  "Apakah anda sering merasa tidak berdaya?",
  "Apakah anda merasa tidak berharga seperti perasaan anda saat kini?",
  "Interpretasi Gejala Depresi",
  "Dapat mengendalikan rangsang buang air besar (BAB)?",
  "Dapat mengendalikan rangsang berkemih/buar air kecil (BAK)?",
  "Membersihkan diri (seka wajah, sisir rambut, sikat gigi)?",
  "Penggunaan jamban (keluar masuk jamban, melepas/memakai celana, membersihkan, menyiram)?",
  "Makan dan Minum (jika makan harus berupa potongan, dianggap dibantu)",
  "Berubah sikap dari berbaring ke duduk",
  "Berpindah/berjalan",
  "Memakai baju",
  "Naik turun tangga",
  "Mandi",
  "Interpretasi ADL (Activity of Daily Living)",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Kesediaan Colok dubur",
  "Hasil Colok Dubur ",
  "Hasil Darah Samar",
  "Jenis Kelamin ",
  "Usia",
  "Apakah pernah didiagnosis/menderita kanker?",
  "Apakah ada keluarga (ayah/ibu/saudara kandung) didiagnosis/menderita kanker sebelumnya?",
  "Riwayat merokok/paparan asap rokok",
  "Riwayat tempat kerja mengandung zat karsinogenik (Pertambangan/ pabrik/ bengkel/ garmen/ bangunan/ laboratorium/ sopir/ galangan kapal, dll)?",
  "Lingkungan tempat tinggal berpotensi tinggi (lingkungan dekat pabrik/pertambangan/buangan sampah, dll)?",
  "Lingkungan dalam rumah yang tidak sehat (ventilasi buruk/atap dari asbes/lantai tanah, dapur tungku, dll)?",
  "Pernah didiagnosis penyakit paru kronik?",
  "Skrining Kanker Paru
intepretasi",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)"
];

// Perempuan 60-69 tahun
const headersPerempuan6069tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Apakah pernah melakukan hubungan intim/seksual?",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Apakah dapat mengingat tiga kata: bunga, pintu, nasi (contoh)?",
  "Tanggal berapakah hari ini secara lengkap (tanggal/bulan/tahun)? atau- Dimanakah Anda saat ini (Puskesmas, rumah, klinik, dll)?",
  "Apakah peserta dapat mengingat tiga kata sebelumnya?",
  "Interpretasi SKILAS Penurunan Kognitif",
  "Mintalah pasien untuk mendengarkan dengan cermat dan mengingat tiga kata dgn pilihan : versi 1: Pisang, bulan, kursi  ; versi 2 ; pemimpin, musim meja  ; versi 3 : desa, dapur, bayi",
  "Katakan seluruh frase berikut sesuai urutannya:  “Tolong gambar sebuah jam pada lembar ini. Mulailah dengan menggambar sebuah lingkaran besar. Kemudian, tuliskan angka-angka pada lingkaran dan atur jarum jam mengarah pukul 11:10 (11 lewat 10 menit).”Bila subjek tidak dapat menyelesaikan gambar jam dalam waktu 3 menit, hentikan pemeriksaan langkah ini dan lanjut ke langkah ke-3.\"",
  "Mintalah pasien untuk MENGULANG 3 kata yang disebutkan pada pertanyaan no 1",
  "Intepretasi Mini-Cog",
  "Apakah klien/pasien lansia mengalami kesulitan dalam membuat keputusan? Misalnya tidak mampu memberi saran dengan benar, tidak mampu mengurus keuangan, membeli hadiah yang tidak layak untuk orang lain, bermasalah dengan pemikiran?",
  "Apakah klien/pasien lansia anda sudah tidak menekuni hobi/ kegiatan yang sebelumnya disenangi? Misalnya merajut, menjahit, berkebun, memasak kue, membaca buku, bermain catur, memainkan alat musik atau bernyanyi?",
  "Apakah keluarga anda mengulang-ngulang pertanyaan, cerita atau pernyataan yang sama?",
  "Apakah klien/pasien lansia mengalami kesulitan belajar menggunakan perkakas dan peralatan? Seperti TV, radio, komputer, microwave, remote control, setrika, blender?",
  "Apakah klien/pasien lansia lupa nama bulan atau tahun?",
  "Apakah klien/pasien lansia mengalami kesulitan mengatur keuangan? Misalnya membayar rekening air/listrik, periksa buku cek, pajak pendapatan, mengambil yang pensiun di bank?",
  "Apakah klien/pasien lansia mengalami kesulitan mengingat janji terhadap orang lain?",
  "Apakah klien/pasien lansia sehari-harinya mengalami gangguan memori dan pemikiran yang konsisten? Misalnya lupa meletakkan kaca mata, kunci kendaraan, meletakkan barang tidak sesuai pada tempatnya?",
  "Interpretasi AD-8",
  "Tes Berdiri di kursi: Berdiri dari kursi lima kali tanpa bantuan tangan. Apakah orang tersebut dapat berdiri dari kursi utuh sebanyak lima kali dalam 14 detik ?",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri berdampingan",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri semi tandem",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri Tandem",
  "tes kecepatan berjalan: Waktu untuk berjalan sejauh empat meter",
  "Tes berdiri dari kursi: Waktu untuk bangkit dari kursi lima kali",
  "Interpretasi SPBB",
  "Apakah berat badan Anda berkurang >3 kg dalam 3 bulan terakhir atau pakaian menjadi lebih longgar?",
  "Apakah Anda hilang nafsu makan Atau mengalami kesulitan makan (misal batuk atau tersedak saat makan, menggunakan selang makan/sonde)?",
  "Apakah ukuran lingkar lengan atas (LiLA) <21 cm?",
  "Interpretasi SKILAS Malnutrisi",
  "Apakah anda mengalami penurunan asupan makanan dalam 3 bulan terakhir disebabkan kehilangan nafsu makan, gangguan saluran cerna, kesulitan mengunyah atau menelan?",
  "Penurunan berat badan dalam tiga bulan terakhir ?",
  "Kemampuan melakukan mobilitas ?",
  "Menderita stress psikologis atau penyakit akut dalam tiga bulan terakhir ?",
  "Mengalami masalah neuropsikologis?",
  "Berapa Nilai IMT (Indeks Massa Tubuh)?",
  "\"Berapa Lingkar Betis? Pertanyaan ini hanya berlaku jika dilapangan tidak ada pengukuran BB dan TB (IMT), jika sdh ada IMT, maka pertanyaan ini tidak perlu ada\"",
  "Interpretasi MNASF",
  "Apakah dalam 2 minggu terakhir Anda merasa sedih, tertekan, atau putus asa?",
  "Apakah dalam 2 minggu terakhir Anda sedikit minat atau kesenangan dalam melakukan sesuatu?",
  "Hasil Skrining Gejala Depresi",
  "Perasaan dalam 2 Minggu terakhir : Apakah anda pada dasarnya puas dengan kehidupan anda?",
  "Menggambarkan perasaan pasien selama dua minggu terakhir:: Apakah anda sering merasa bosan?",
  "Apakah anda sering merasa tidak berdaya?",
  "Apakah anda merasa tidak berharga seperti perasaan anda saat kini?",
  "Interpretasi Gejala Depresi",
  "Dapat mengendalikan rangsang buang air besar (BAB)?",
  "Dapat mengendalikan rangsang berkemih/buar air kecil (BAK)?",
  "Membersihkan diri (seka wajah, sisir rambut, sikat gigi)?",
  "Penggunaan jamban (keluar masuk jamban, melepas/memakai celana, membersihkan, menyiram)?",
  "Makan dan Minum (jika makan harus berupa potongan, dianggap dibantu)",
  "Berubah sikap dari berbaring ke duduk",
  "Berpindah/berjalan",
  "Memakai baju",
  "Naik turun tangga",
  "Mandi",
  "Interpretasi ADL (Activity of Daily Living)",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)",
  "Pilih jenis pemeriksaan yang dilakukan",
  "Hasil pemeriksaan SADANIS",
  "Hasil pemeriksaan USG Payudara",
  "Pemeriksaan Inspekulo",
  "Pemeriksaan Inspeksi Visual Asam Asetat (IVA)",
  "Isi hasil pemeriksaan DNA HPV"
];

// Perempuan >=70 tahun
const headersPerempuan70tahun = [
,
  "Nama Provinsi",
  "Nama Kabupaten/ kota",
  "Nama faskes",
  "Kode faskes ",
  "NIK ",
  "Nama Lengkap",
  "Tanggal Lahir (DD/MM/YYYY)",
  "Jenis Kelamin",
  "No WA",
  "Status Perkawinan",
  "Apabila belum menikah/ status cerai, apakah ada rencana menikah dalam kurun waktu 1 tahun ke depan?",
,
  "Apakah Anda merokok dalam setahun terakhir ini?",
  "Sudah berapa tahun Anda merokok?",
  "Biasanya, berapa batang rokok yang Anda hisap dalam sehari?",
  "Apakah Anda pernah merokok sebelumnya?",
  "Berapa lama (tahun) Anda merokok sebelumnya?",
  "Kapan Anda berhenti merokok?",
  "Apakah Anda terpapar asap rokok atau menghirup asap rokok dari orang lain dalam sebulan terakhir?",
  "Apakah Anda rutin melakukan olahraga, (seperti jalan cepat, lari, bersepeda, senam, berenang, bulutangkis, sepakbola atau olahraga lainnya)?",
  "Dalam seminggu terakhir, berapa kali Anda berolahraga?",
  "Berapa menit biasanya anda melakukan olahraga tersebut setiap satu kali olahraga?",
  "Tingkat Aktivitas Fisik",
  "Apakah Anda pernah dinyatakan tekanan darah tinggi?",
  "Apakah Anda pernah dinyatakan diabetes atau kencing manis?",
  "Apakah Anda pernah atau sedang mengalami batuk yang tidak sembuh-sembuh selama lebih dari 2 minggu?",
  "Apakah Anda tinggal serumah atau sering bertemu dengan orang yang menderita Tuberkulosis (TBC) atau batuk berkepanjangan?",
  "Gejala/Riwayat Kontak Tuberkulosis",
  "Dalam 2 minggu terakhir, seberapa sering anda kurang/ tidak bersemangat dalam melakukan kegiatan sehari-hari?",
  "Dalam 2 minggu terakhir, seberapa sering anda merasa murung, tertekan, atau putus asa?",
  "Gejala Depresi",
  "Dalam 2 minggu terakhir,  seberapa sering anda merasa gugup, cemas, atau gelisah?",
  "Dalam 2 minggu terakhir,  seberapa sering anda tidak mampu mengendalikan rasa khawatir?",
  "Gejala Kecemasan",
  "Apakah Anda pernah menjalani tes untuk Hepatitis B dan mendapatkan hasil positif?",
  "Apakah Anda memiliki ibu kandung/saudara sekandung yang menderita Hepatitis B?",
  "Apakah Anda pernah melakukan hubungan intim / seksual dengan orang yang bukan pasangan resmi Anda?",
  "Apakah Anda pernah menerima transfusi darah sebelumnya?",
  "Apakah Anda pernah menjalani cuci darah  atau hemodialisis?",
  "Apakah Anda pernah menggunakan narkoba, obat terlarang, atau bahan adiktif lainnya dengan cara disuntik?",
  "Apakah Anda adalah orang dengan HIV (ODHIV)?",
  "Apakah Anda pernah mendapatkan pengobatan Hepatitis C dan tidak sembuh?",
  "Apakah Anda pernah didiagnosa atau mendapatkan hasil pemeriksaan kolesterol (lemak darah) tinggi?",
  "Faktor Risiko Hepatitis B",
  "Faktor Risiko Hepatitis C",
  "Faktor Risiko Hepatitis",
  "Berat Badan (Kg)",
  "Pengukuran Tinggi Badan (cm)",
  "Index Massa Tubuh",
  "Pengukuran Lingkar Perut",
  "Tekanan Darah Sistolik",
  "Tekanan Darah Diastolik",
  "Hasil Tekanan Darah",
  "Gula Darah Sewaktu (GDS) (mg/dl)",
  "Gula Darah Puasa (GDP) (mg/dl)",
  "Apakah dapat mengingat tiga kata: bunga, pintu, nasi (contoh)?",
  "Tanggal berapakah hari ini secara lengkap (tanggal/bulan/tahun)? atau- Dimanakah Anda saat ini (Puskesmas, rumah, klinik, dll)?",
  "Apakah peserta dapat mengingat tiga kata sebelumnya?",
  "Interpretasi SKILAS Penurunan Kognitif",
  "Mintalah pasien untuk mendengarkan dengan cermat dan mengingat tiga kata dgn pilihan : versi 1: Pisang, bulan, kursi  ; versi 2 ; pemimpin, musim meja  ; versi 3 : desa, dapur, bayi",
  "Katakan seluruh frase berikut sesuai urutannya:  “Tolong gambar sebuah jam pada lembar ini. Mulailah dengan menggambar sebuah lingkaran besar. Kemudian, tuliskan angka-angka pada lingkaran dan atur jarum jam mengarah pukul 11:10 (11 lewat 10 menit).”Bila subjek tidak dapat menyelesaikan gambar jam dalam waktu 3 menit, hentikan pemeriksaan langkah ini dan lanjut ke langkah ke-3.\"",
  "Mintalah pasien untuk MENGULANG 3 kata yang disebutkan pada pertanyaan no 1",
  "Intepretasi Mini-Cog",
  "Apakah klien/pasien lansia mengalami kesulitan dalam membuat keputusan? Misalnya tidak mampu memberi saran dengan benar, tidak mampu mengurus keuangan, membeli hadiah yang tidak layak untuk orang lain, bermasalah dengan pemikiran?",
  "Apakah klien/pasien lansia anda sudah tidak menekuni hobi/ kegiatan yang sebelumnya disenangi? Misalnya merajut, menjahit, berkebun, memasak kue, membaca buku, bermain catur, memainkan alat musik atau bernyanyi?",
  "Apakah keluarga anda mengulang-ngulang pertanyaan, cerita atau pernyataan yang sama?",
  "Apakah klien/pasien lansia mengalami kesulitan belajar menggunakan perkakas dan peralatan? Seperti TV, radio, komputer, microwave, remote control, setrika, blender?",
  "Apakah klien/pasien lansia lupa nama bulan atau tahun?",
  "Apakah klien/pasien lansia mengalami kesulitan mengatur keuangan? Misalnya membayar rekening air/listrik, periksa buku cek, pajak pendapatan, mengambil yang pensiun di bank?",
  "Apakah klien/pasien lansia mengalami kesulitan mengingat janji terhadap orang lain?",
  "Apakah klien/pasien lansia sehari-harinya mengalami gangguan memori dan pemikiran yang konsisten? Misalnya lupa meletakkan kaca mata, kunci kendaraan, meletakkan barang tidak sesuai pada tempatnya?",
  "Interpretasi AD-8",
  "Tes Berdiri di kursi: Berdiri dari kursi lima kali tanpa bantuan tangan. Apakah orang tersebut dapat berdiri dari kursi utuh sebanyak lima kali dalam 14 detik ?",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri berdampingan",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri semi tandem",
  "Tes keseimbangan: berdiri selama 10 detik dengan kaki di masing-masing : Berdiri Tandem",
  "tes kecepatan berjalan: Waktu untuk berjalan sejauh empat meter",
  "Tes berdiri dari kursi: Waktu untuk bangkit dari kursi lima kali",
  "Interpretasi SPBB",
  "Apakah berat badan Anda berkurang >3 kg dalam 3 bulan terakhir atau pakaian menjadi lebih longgar?",
  "Apakah Anda hilang nafsu makan Atau mengalami kesulitan makan (misal batuk atau tersedak saat makan, menggunakan selang makan/sonde)?",
  "Apakah ukuran lingkar lengan atas (LiLA) <21 cm?",
  "Interpretasi SKILAS Malnutrisi",
  "Apakah anda mengalami penurunan asupan makanan dalam 3 bulan terakhir disebabkan kehilangan nafsu makan, gangguan saluran cerna, kesulitan mengunyah atau menelan?",
  "Penurunan berat badan dalam tiga bulan terakhir ?",
  "Kemampuan melakukan mobilitas ?",
  "Menderita stress psikologis atau penyakit akut dalam tiga bulan terakhir ?",
  "Mengalami masalah neuropsikologis?",
  "Berapa Nilai IMT (Indeks Massa Tubuh)?",
  "\"Berapa Lingkar Betis? Pertanyaan ini hanya berlaku jika dilapangan tidak ada pengukuran BB dan TB (IMT), jika sdh ada IMT, maka pertanyaan ini tidak perlu ada\"",
  "Interpretasi MNASF",
  "Apakah dalam 2 minggu terakhir Anda merasa sedih, tertekan, atau putus asa?",
  "Apakah dalam 2 minggu terakhir Anda sedikit minat atau kesenangan dalam melakukan sesuatu?",
  "Hasil Skrining Gejala Depresi",
  "Perasaan dalam 2 Minggu terakhir : Apakah anda pada dasarnya puas dengan kehidupan anda?",
  "Menggambarkan perasaan pasien selama dua minggu terakhir:: Apakah anda sering merasa bosan?",
  "Apakah anda sering merasa tidak berdaya?",
  "Apakah anda merasa tidak berharga seperti perasaan anda saat kini?",
  "Interpretasi Gejala Depresi",
  "Dapat mengendalikan rangsang buang air besar (BAB)?",
  "Dapat mengendalikan rangsang berkemih/buar air kecil (BAK)?",
  "Membersihkan diri (seka wajah, sisir rambut, sikat gigi)?",
  "Penggunaan jamban (keluar masuk jamban, melepas/memakai celana, membersihkan, menyiram)?",
  "Makan dan Minum (jika makan harus berupa potongan, dianggap dibantu)",
  "Berubah sikap dari berbaring ke duduk",
  "Berpindah/berjalan",
  "Memakai baju",
  "Naik turun tangga",
  "Mandi",
  "Interpretasi ADL (Activity of Daily Living)",
  "Usia - skor PUMA",
  "Apakah anda sedang/mempunyai riwayat merokok?",
  "Jika Perokok Aktif, berapa bungkus per tahun?",
  "Apakah Anda pernah merasa napas pendek ketika berjalan lebih cepat pada jalan yang datar atau pada jalan yang sedikit menanjak?",
  "Apakah Anda biasanya mempunyai dahak yang berasal dari paru atau kesulitan mengeluarkan dahak saat Anda sedang tidak menderita selesma/flu?",
  "Apakah Anda biasanya batuk saat sedang tidak menderita selesma/flu?",
  "Apakah Dokter atau tenaga medis lainnya pernah meminta Anda untuk melakukan pemeriksaan spirometri atau peak flow meter (meniup ke dalam suatu alat) untuk mengetahui fungsi paru?",
  "Hasil Skor Kuesioner PUMA",
  "Pemeriksaan Gula Darah Puasa (GDP) (mg/dl)",
  "Pemeriksaan Gula Darah 2 Jam PP (mg/dl)",
  "Pemeriksaan Hb1AC",
  "Hasil Rapid Test Hepatitis B",
  "Hasil Rapid Test Hepatitis C",
  "Nilai SGOT",
  "Pemeriksaan Trombosit",
  "Hasil APRI Score (hitung manual dari kalkulator online APRI Score)",
  "Nilai Hasil Pemeriksaan Ureum",
  "Hasil Pemeriksaan Kreatinin",
  "Nilai Hasil pemeriksaan (e-LFG (CKD-EPI))",
  "Kolesterol Total",
  "Interpretasi Kolesterol Total",
  "Masukkan nilai HDL",
  "Interpretasi HDL",
  "Masukkan nilai LDL",
  "Interpretasi LDL",
  "Masukkan nilai Trigliserida",
  "Interpretasi Trigliserida",
  "Interpretasi Dislipidemia",
  "Prediksi Risiko Penyakit Kardiovaskular",
  "Metode Pemeriksaan",
  "Hasil Pemeriksaan TB TCM",
  "Hasil Pemeriksaan BTA",
  "Hasil pemeriksaan tajam pendengaran",
  "Pemeriksaan Otoskop dan/atau Penala",
  "Pemeriksaan visus (E-Tumbling)",
  "Pemeriksaan visus (snellen chart)",
  "Pemeriksaan Pinhole",
  "Hasil pemeriksaan pupil",
  "Pemeriksaan Gigi - Gigi Karies",
  "Pemeriksaan Gigi - Gigi hilang/dicabut",
  "Pocket Periodontal",
  "Gigi Goyang",
  "Hasil Pemeriksaan EKG",
  "Pemeriksaan EKG (Jika hasil EKG abnormal, maka pilih hasil berikut)"
];

